In [8]:
import import_ipynb

In [29]:
from text.inference import predict_emotion

In [1]:
import pickle

In [3]:
with open(r"C:\Users\Saikat Maiti\Desktop\Music recommendation\music\musicdata.pkl", "rb") as f:
    df = pickle.load(f)

In [4]:
df

,Artist(s),song,emotion,description
0,!!!,Even When the Waters Cold,sadness,friend told her she wa better off at the botto...
1,!!!,One Girl / One Boy,sadness,"well i heard it, play soft from a drunken bar'..."
2,!!!,Pardon My Freedom,joy,"oh my god, did i just say that out loud? shoul..."
3,!!!,Ooo,joy,[vers 1] rememb when i call you on the telepho...
4,!!!,Freedom 15,joy,[vers 1] call me like i got someth to say you ...
...,...,...,...,...
551438,박혜진 Park Hye Jin,Can you,joy,can you be my (can you be my) can you be my (c...
551439,심형진 Hyungjin Sim,Lim Han Byul Lee Hyuk - Prayer English Transl...,joy,[verse] i gave you my everyth but i see i can'...
551440,우정하,Memories Smiling Tears Remix,sadness,"[tasha] hell on earth, watch all live pass by ..."
551441,제노,Come Back to Me,sadness,[verse] gift and flower lay upon the lid of pi...
551442,코케,I Wanna Be With You,love,i wanna b with you i wanna b with you babi yea...

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [16]:
cv.fit(df["description"])

CountVectorizer(max_features=5000, stop_words='english')

In [31]:
with open('count_vectorizer.pkl','wb') as f:
    pickle.dump(cv,f)

In [22]:
def similar(text1,text2):
    v1 = cv.transform([text1])
    v2 = cv.transform([text2])

    score = cosine_similarity(v1, v2)

    return float(score[0][0])

In [23]:
def recommend_songs(user_context,
                    final_emotion,
                    music_df):

    filtered = music_df[
        music_df["emotion"] == final_emotion
    ]

    scores = []

    for _, row in filtered.iterrows():

        score = similar(
            user_context,
            row["description"]
        )

        scores.append(
            (
                row["song"],
                score
            )
        )

    scores.sort(
        key=lambda x: x[1],
        reverse=True
    )

    return scores[:10]

In [19]:
user_text = "i am feel very happy today"

In [20]:
emotion, confidence = predict_emotion(user_text)
print(emotion, confidence)

joy 0.9998430013656616

In [24]:
recommendations = recommend_songs(
    user_context=user_text,
    final_emotion=emotion,
    music_df=df
)

In [27]:
print("\nRecommended Songs:\n")

for rank, (song, score) in enumerate(recommendations, start=1):
    print(f"{rank}. {song}")

Recommended Songs:

1. Happy
2. Happy
3. Happy
4. Happy
5. Happy
6. Feeling Rich Today Remix
7. Feeling Rich Today
8. How Do U Feel Remix
9. How Do U Feel
10. 8 Ball

In [28]:
df[df['song']=='Happy']

,Artist(s),song,emotion,description
1755,17 Memphis,Happy,sadness,i can't think about it it' too hard to face to...
16979,Alexia,Happy,joy,you know what i'm saying? happi it' so nice to...
22614,Amy Grant,Happy,joy,i wanna look behind your eye and gentli brush ...
26530,"Annabel Jones,k?d",Happy,sadness,"[vers 1] i feel tired, i look it, too tear me ..."
29418,Ardhito Pramono,Happy,joy,[verse] let the past be memori 'caus we'r now ...
...,...,...,...,...
532958,"Will Ferrell,My Marianne",Happy,joy,[chorus: will ferrel & molli sandén] (becaus i...
532959,"Will Ferrell,My Marianne",Happy,joy,[chorus: will ferrel & molli sandén] (becaus i...
532961,"Will Ferrell,My Marianne",Happy,joy,[chorus: will ferrel & molli sandén] (becaus i...
536732,"Wretch 32,J Warner",Happy,joy,[intro] she ain't 5 foot 2 she be 5 foot cute ...
544410,Young Rising Sons,Happy,sadness,[intro] i'v been go to some dark place i hate ...